import { useEffect,useState } from 'react';
import { useNavigate,useParams } from 'react-router-dom';
import { getFlightById } from '../services/flightService';
import { createBooking } from '../services/bookingService';
import { errorMessage,formatDateTime,money,unwrap } from '../utils';
import Alert from '../components/Alert';

const empty=()=>({name:'',age:'',gender:'MALE',seatNumber:'',contact:''});
export default function PassengerDetails(){const {flightId}=useParams();const navigate=useNavigate();const [flight,setFlight]=useState(null);const [passengers,setPassengers]=useState([empty()]);const [paymentMode,setPaymentMode]=useState('UPI');const [error,setError]=useState('');const [loading,setLoading]=useState(false);
useEffect(()=>{getFlightById(flightId).then(r=>setFlight(unwrap(r))).catch(e=>setError(errorMessage(e)))},[flightId]);
const update=(i,k,v)=>setPassengers(p=>p.map((x,n)=>n===i?{...x,[k]:v}:x)); const add=()=>{if(passengers.length<Number(flight?.availableSeats||1))setPassengers([...passengers,empty()])}; const remove=i=>setPassengers(p=>p.filter((_,n)=>n!==i));
const submit=async e=>{e.preventDefault();setError('');if(passengers.some(p=>!p.name||!p.age||!p.seatNumber||!/^[0-9]{10}$/.test(p.contact))){setError('Fill every passenger field and use a valid 10-digit contact number.');return;}setLoading(true);try{const booking={passengers:passengers.map(p=>({...p,age:Number(p.age)})),payment:{modeOfPayment:paymentMode}};const saved=unwrap(await createBooking(flightId,booking));navigate(`/booking/${saved.bookingId}`,{state:{booking:saved}});}catch(e){setError(errorMessage(e));}finally{setLoading(false)}};
if(!flight)return <main className="page"><Alert>{error}</Alert>{!error&&'Loading flight...'}</main>;
return <main className="page"><div className="steps"><span className="active">1 Passenger details</span><span>2 Payment</span><span>3 Confirmation</span></div><form onSubmit={submit}><div className="form-layout"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">Travellers</span><h2>Passenger details</h2></div><span>{passengers.length}/{flight.availableSeats} seats</span></div>{passengers.map((p,i)=><div className="passenger-form" key={i}><div className="passenger-title"><strong>Passenger {i+1}</strong>{passengers.length>1&&<button type="button" className="danger-link" onClick={()=>remove(i)}>Remove</button>}</div><div className="form-grid"><label>Full name<input required value={p.name} onChange={e=>update(i,'name',e.target.value)} /></label><label>Age<input required min="1" max="120" type="number" value={p.age} onChange={e=>update(i,'age',e.target.value)} /></label><label>Gender<select value={p.gender} onChange={e=>update(i,'gender',e.target.value)}><option>MALE</option><option>FEMALE</option><option>OTHER</option></select></label><label>Seat number<input required placeholder="12A" value={p.seatNumber} onChange={e=>update(i,'seatNumber',e.target.value.toUpperCase())}/></label><label className="wide">Contact number<input required maxLength="10" value={p.contact} onChange={e=>update(i,'contact',e.target.value.replace(/\D/g,''))} placeholder="10 digit number"/></label></div></div>)}<button type="button" className="outline" onClick={add} disabled={passengers.length>=flight.availableSeats}>+ Add passenger</button></section>
<section className="panel"><span className="eyebrow">Payment</span><h2>Choose payment mode</h2><div className="payment-options">{['UPI','CREDIT_CARD','DEBIT_CARD','NET_BANKING'].map(m=><label className={paymentMode===m?'payment-option selected':'payment-option'} key={m}><input type="radio" name="payment" checked={paymentMode===m} onChange={()=>setPaymentMode(m)}/><b>{m.replace('_',' ')}</b><span>Available</span></label>)}</div><Alert>{error}</Alert><button className="primary big full" disabled={loading}>{loading?'Processing...':`Pay ${money(Number(flight.price)*passengers.length)} & Confirm`}</button></section></div></form><aside className="summary-card"><span className="eyebrow">Trip summary</span><h3>{flight.source} → {flight.destination}</h3><p>{flight.airline} · {formatDateTime(flight.departureDateTime)}</p><div className="summary-total"><span>{passengers.length} passenger(s)</span><strong>{money(Number(flight.price)*passengers.length)}</strong></div></aside></main>}
